### PR TITLE
Support Browserify's ability to require JSON files

### PR DESCRIPTION
**Pull request by jackwanders**
For some time, node has supported the ability to directly require `.json` files, as described in the Modules documentation:

https://nodejs.org/api/modules.html#modules_file_modules

Browserify supports this same functionality by prepending the source for any required `.json` file with `module.exports = `.

https://github.com/substack/node-browserify/blob/master/index.js#L601

Unfortunately, because `folderify`, as a transform, acts on the source before it's passed to `browserify`, it receives only the JSON source and attempts to parse it with `falafel`. When `acorn` eventually tries to create an AST for this JSON source, it fails as JSON alone doesn't represent a well-formed JavaScript document.

This pull request adds the expectation that the application being bundled with `browserify` may contain non-JavaScript require targets. When `parse()` is called, we check to see if the extension of `itsFileName` represents something that can be parsed by `falafel`; `''` for folders (i.e. targets of `includeFolder`) and `.js` for JavaScript files. If the filename represents any other file type, simply pass the source directly to `finish()`.

### CODE REVIEW

**Comment by parroit** [comment]
Thank you for your PR. I looked at your changes and it look goods. 
I don't understand why you allow '' extension. You told it's for folder, or targets of includeFolder, but this files are not actually parsed by falafel. 
Could you please explain further on this point?

**Comment by jackwanders** [comment]
If I log each call to `folderify()` and the value of the `file` argument provided to it, I get the following when I run `npm test`:

```bash
  folderify
    ✓ is defined
folderify(./test/files)
    ✓ return a through stream
folderify(./test/files)
    ✓ un-require include-folder
folderify(./test/files)
    ✓ skip hidden files
folderify(./test/files)
    ✓ include hidden files
folderify(./test/files)
    ✓ preserve filenames
folderify(/jackwanders/folderify/test/fixtures/source.js)
    ✓ doesn't require brfs (60ms)
folderify(/jackwanders/folderify/test/fixtures/source.js)
    ✓ is compatible with brfs (44ms)
folderify(/jackwanders/folderify/test/fixtures/source.js)
    ✓ support transforms in both order
folderify(/jackwanders/folderify/test/fixtures/source-with-json.js)
folderify(/jackwanders/folderify/test/fixtures/data.json)
    ✓ support bundles with json requires (52ms)
```

In normal use cases, `folderify()` is called on each source filename that is recognized by `browserify` as part of the dependency tree of the root module.

However, note that in the first few tests, you call `folderify()` directly on `./test/files`. I haven't dug into the code enough to see why these tests are written with such a call, as it doesn't appear on the surface to be a valid real-world use case, but either way, `isParsableFilename()` needs to return true for `./test/files` if we want to have the expected output.

I'm open to changing this logic if there's another way to address the case where `folderify` is called directly on a folder path as opposed to a file path.

**Comment by parroit** [comment]
Ah ok, understood. It's tests that are wrong coded. 
The file argument was used only to eventually replace any __filename or __dirname 
in the source file with actual filename and dirname.

Since tests that use `checkTransform` never cover this use case, I didn't care of the filename 
I pass to the function, and gave a path without extension.

I think this will never happen in a real case, so it is safe to remove the empty extension from the allowed ones and change the tests to use a .js extension in `checkTransform`.

Could you take care of this?

Just another thing. If you look at this [babel doc page](http://babeljs.io/docs/usage/cli/) it appear there are more used extensions for javascript files. I already used .jsx for example.
I think it's better to include the extensions specified there within the allowed ones, and maybe 
in the future include an addition option to allow users to customize allowed extensions.

What do you think about?

**Comment by jackwanders** [comment]
I think the most appropriate thing to do would be to move the `source` and `expected` strings from the first four tests into individual `source.js` and `expected.js` files within the `/test/fixtures` directory. You should then be able to call `folderify(./test/fixtures/unrequire-if/source.js)` (or similar) and validate that the output matches the contents of the associated `expected.js` file.

Also, it's worth noting that the final three tests (four in my branch) would break if `browserify` changed the way it wrapped modules; your `expected-bundle.js` file includes code generated by `browserify`. Because `folderify` only concerns itself with massaging the contents of individual files, it may not be appropriate to validate the full contents of the generated bundle. If you want to validate that `folderify` works appropriately as a `browserify` plugin, you should be able to do so by creating a bundle with browserify, including `folderify` as a transform, and then validating that the bundling process doesn't fail and that all references to `include-folder` have been removed from the generated bundle. The previous tests that validate the functionality of `folderify()` directly should give you the confidence you need that it will continue working as expected when used within `browserify`.

**Comment by jackwanders** [comment]
I've added a commit that refactors `folderify_test.js` to rely fully on files within the `fixtures` directory for both source files to pass to `folderify()` and `browserify()` as well as expected output of these operations.

The case of calling `folderify()` on a directory has been removed, and I have also added the default babel-parsable extensions to Folderify's whitelist (even though `falafel` uses `acorn`, it's a safe list).

**Comment by parro-it** [comment]
Thank you @jackwanders, great work! I merged this on master. Since I think this is a breaking change and I'm thinkng of switching the package to semver, I will publish a 1.0.0 version soon on npm

**Comment by jackwanders** [comment]
Awesome; thanks @parro-it!

**Comment by nchase** [comment]
:thumbsup: this is really useful!

**Comment by parro-it** [comment]
:clap: goes to Jack

**Pull request merged**
